export const DEMO_STORAGE_KEY = 'mutqin.demo.v1';
export const DEMO_STATE_VERSION = 1;

export interface DemoEvent {
  id: string;
  title: string;
  titleEn?: string;
  titleAr?: string;
  organizerEn?: string;
  organizerAr?: string;
  descriptionEn?: string;
  descriptionAr?: string;
  date?: string;
  locationEn?: string;
  locationAr?: string;
  city?: string;
  specialty?: string;
  activityType?: string;
  cme_hours?: number;
  is_sponsored?: boolean;
  needs_sponsorship?: boolean;
  sfda_license?: string;
  status: 'draft' | 'pending_review' | 'approved' | 'published' | 'closed';
  organizerId: string;
  submittedAt?: string;
  decisionAt?: string;
  rejectionReason?: string;
  rejectionCategory?: string;
}

export interface DemoAssignment {
  id: string;
  eventId: string;
  organizerId: string;
  eventManagerId: string;
  status: 'pending' | 'accepted' | 'declined';
}

export interface DemoTicket {
  id: string;
  eventId: string;
  hcpId: string;
  status: 'confirmed' | 'attended';
}

export interface DemoAttendance {
  id: string;
  ticketId: string;
  finalized: boolean;
}

export interface DemoCertificate {
  id: string;
  eventId: string;
  ticketId: string;
  hcpId: string;
  verified?: boolean;
  cme_hours?: number;
  issuedAt?: string;
  url?: string;
}

export interface DemoReview {
  id: string;
  eventId: string;
  hcpId: string;
  rating: number;
  text?: string;
  comment?: string;
  createdAt?: string;
  date?: string;
}

export interface DemoSponsorship {
  id: string;
  eventId: string;
  vendorId: string;
  status: 'purchased';
  package?: string;
}

export interface DemoState {
  version: number;
  events: DemoEvent[];
  assignments: DemoAssignment[];
  tickets: DemoTicket[];
  attendanceRecords: DemoAttendance[];
  certificates: DemoCertificate[];
  reviews: DemoReview[];
  sponsorships: DemoSponsorship[];
}

/**
 * Deterministic seed data for the demo store.
 * Contains a single happy-path scenario across roles.
 */
export function seedDemoState(): DemoState {
  const organizerId = 'org-1';
  const eventManagerId = 'em-1';
  const hcpId = 'hcp-1';
  const vendorId = 'vendor-1';
  const eventId = 'evt-1';
  const assignmentId = 'assign-1';
  const ticketId = 'tkt-1';
  const attendanceId = 'att-1';
  const certificateId = 'cert-1';
  const reviewId = 'rev-1';
  const sponsorshipId = 'spon-1';

  return {
    version: DEMO_STATE_VERSION,
    events: [
      {
        id: eventId,
        title: 'Accredited Event',
        titleEn: 'Accredited Event',
        titleAr: ' ',
        organizerEn: 'Demo Organizer',
        organizerAr: ' ',
        descriptionEn: 'Seeded accredited event used across the demo flow.',
        descriptionAr: '      .',
        date: '2025-01-15',
        locationEn: 'Riyadh - Conference Center',
        locationAr: ' -  ',
        city: 'Riyadh',
        specialty: 'cardiology',
        activityType: 'Conference',
        cme_hours: 12,
        is_sponsored: false,
        needs_sponsorship: true,
        sfda_license: 'MDS-REQ-2024-001',
        status: 'published',
        organizerId,
        submittedAt: '2024-12-01T10:00:00Z',
        decisionAt: '2024-12-05T14:30:00Z',
      },
      {
        id: 'evt-2',
        title: 'Pediatrics Workshop',
        titleEn: 'Pediatrics Workshop',
        titleAr: '   ',
        organizerEn: 'Children Hospital',
        organizerAr: ' ',
        descriptionEn: 'Advanced pediatrics training.',
        descriptionAr: '    ',
        date: '2025-02-10',
        locationEn: 'Jeddah - Medical Center',
        locationAr: ' -  ',
        city: 'Jeddah',
        specialty: 'pediatrics',
        activityType: 'Workshop',
        cme_hours: 8,
        sfda_license: 'MDS-REQ-2024-002',
        status: 'pending_review',
        organizerId,
        submittedAt: '2024-12-15T09:00:00Z',
      },
      {
        id: 'evt-3',
        title: 'Emergency Medicine Symposium',
        titleEn: 'Emergency Medicine Symposium',
        titleAr: '  ',
        organizerEn: 'Medical Association',
        organizerAr: ' ',
        descriptionEn: 'Latest in emergency care.',
        descriptionAr: '    ',
        date: '2025-03-20',
        locationEn: 'Dammam - King Fahd Hospital',
        locationAr: ' -   ',
        city: 'Dammam',
        specialty: 'emergency_medicine',
        activityType: 'Symposium',
        cme_hours: 15,
        sfda_license: 'MDS-REQ-2024-003',
        status: 'approved',
        organizerId,
        submittedAt: '2024-11-20T11:00:00Z',
        decisionAt: '2024-11-25T16:00:00Z',
      },
      {
        id: 'evt-4',
        title: 'Family Medicine Update',
        titleEn: 'Family Medicine Update',
        titleAr: '  ',
        organizerEn: 'Primary Care Institute',
        organizerAr: '  ',
        descriptionEn: 'Family practice updates.',
        descriptionAr: '  ',
        date: '2025-04-05',
        locationEn: 'Riyadh - Health Hub',
        locationAr: ' -  ',
        city: 'Riyadh',
        specialty: 'family_medicine',
        activityType: 'Seminar',
        cme_hours: 6,
        sfda_license: 'MDS-REQ-2024-004',
        status: 'draft',
        organizerId,
        submittedAt: '2024-12-10T13:00:00Z',
        decisionAt: '2024-12-12T10:00:00Z',
        rejectionReason: 'Incomplete documentation',
        rejectionCategory: 'Documentation',
      },
      {
        id: 'evt-5',
        title: 'Surgical Skills Course',
        titleEn: 'Surgical Skills Course',
        titleAr: '  ',
        organizerEn: 'Surgical Center',
        organizerAr: ' ',
        descriptionEn: 'Hands-on surgical training.',
        descriptionAr: '  ',
        date: '2025-05-12',
        locationEn: 'Jeddah - Surgical Institute',
        locationAr: ' -  ',
        city: 'Jeddah',
        specialty: 'General Surgery',
        activityType: 'Course',
        cme_hours: 20,
        sfda_license: 'MDS-REQ-2024-005',
        status: 'pending_review',
        organizerId,
        submittedAt: '2024-12-18T08:30:00Z',
      },
      // Additional events for Queue (6+ items requirement)
      {
        id: 'evt-6',
        title: 'Oncology Conference',
        titleEn: 'Oncology Conference',
        titleAr: ' ',
        organizerEn: 'Cancer Institute',
        organizerAr: ' ',
        descriptionEn: 'Latest in cancer treatment.',
        descriptionAr: '    ',
        date: '2025-06-01',
        locationEn: 'Riyadh - Medical Complex',
        locationAr: ' -  ',
        city: 'Riyadh',
        specialty: 'Oncology',
        activityType: 'Conference',
        cme_hours: 18,
        sfda_license: 'MDS-REQ-2024-006',
        status: 'pending_review',
        organizerId,
        submittedAt: '2024-12-20T10:00:00Z',
      },
      {
        id: 'evt-7',
        title: 'Neurology Workshop',
        titleEn: 'Neurology Workshop',
        titleAr: '   ',
        organizerEn: 'Neurological Center',
        organizerAr: ' ',
        descriptionEn: 'Advanced neurology techniques.',
        descriptionAr: '    ',
        date: '2025-07-15',
        locationEn: 'Dammam - Neurological Institute',
        locationAr: ' -  ',
        city: 'Dammam',
        specialty: 'neurology',
        activityType: 'Workshop',
        cme_hours: 10,
        sfda_license: 'MDS-REQ-2024-007',
        status: 'pending_review',
        organizerId,
        submittedAt: '2024-12-22T14:00:00Z',
      },
      {
        id: 'evt-8',
        title: 'Orthopedics Seminar',
        titleEn: 'Orthopedics Seminar',
        titleAr: '  ',
        organizerEn: 'Orthopedic Hospital',
        organizerAr: ' ',
        descriptionEn: 'Bone and joint care updates.',
        descriptionAr: '   ',
        date: '2025-08-10',
        locationEn: 'Jeddah - Orthopedic Center',
        locationAr: ' -  ',
        city: 'Jeddah',
        specialty: 'Orthopedics',
        activityType: 'Seminar',
        cme_hours: 7,
        sfda_license: 'MDS-REQ-2024-008',
        status: 'pending_review',
        organizerId,
        submittedAt: '2024-12-25T09:00:00Z',
      },
      {
        id: 'evt-9',
        title: 'Dermatology Update',
        titleEn: 'Dermatology Update',
        titleAr: '  ',
        organizerEn: 'Skin Care Clinic',
        organizerAr: '  ',
        descriptionEn: 'Latest in dermatology.',
        descriptionAr: '    ',
        date: '2025-09-05',
        locationEn: 'Riyadh - Dermatology Center',
        locationAr: ' -  ',
        city: 'Riyadh',
        specialty: 'dermatology',
        activityType: 'Seminar',
        cme_hours: 5,
        sfda_license: 'MDS-REQ-2024-009',
        status: 'pending_review',
        organizerId,
        submittedAt: '2024-12-28T11:00:00Z',
      },
      {
        id: 'evt-10',
        title: 'Psychiatry Symposium',
        titleEn: 'Psychiatry Symposium',
        titleAr: '  ',
        organizerEn: 'Mental Health Center',
        organizerAr: '  ',
        descriptionEn: 'Mental health advances.',
        descriptionAr: '  ',
        date: '2025-10-20',
        locationEn: 'Dammam - Mental Health Institute',
        locationAr: ' -   ',
        city: 'Dammam',
        specialty: 'Psychiatry',
        activityType: 'Symposium',
        cme_hours: 14,
        sfda_license: 'MDS-REQ-2024-010',
        status: 'pending_review',
        organizerId,
        submittedAt: '2024-12-30T08:00:00Z',
      },
      // Additional events for Decisions (10+ items requirement)
      {
        id: 'evt-11',
        title: 'Cardiology Advanced',
        titleEn: 'Cardiology Advanced',
        titleAr: '  ',
        organizerEn: 'Heart Center',
        organizerAr: ' ',
        descriptionEn: 'Advanced cardiac care.',
        descriptionAr: '  ',
        date: '2025-11-01',
        locationEn: 'Riyadh - Cardiac Institute',
        locationAr: ' -  ',
        city: 'Riyadh',
        specialty: 'cardiology',
        activityType: 'Conference',
        cme_hours: 16,
        sfda_license: 'MDS-REQ-2024-011',
        status: 'approved',
        organizerId,
        submittedAt: '2024-11-10T10:00:00Z',
        decisionAt: '2024-11-15T15:00:00Z',
      },
      {
        id: 'evt-12',
        title: 'Endocrinology Workshop',
        titleEn: 'Endocrinology Workshop',
        titleAr: '   ',
        organizerEn: 'Endocrine Center',
        organizerAr: '  ',
        descriptionEn: 'Hormone disorders management.',
        descriptionAr: '  ',
        date: '2025-12-05',
        locationEn: 'Jeddah - Endocrine Institute',
        locationAr: ' -   ',
        city: 'Jeddah',
        specialty: 'endocrinology',
        activityType: 'Workshop',
        cme_hours: 9,
        sfda_license: 'MDS-REQ-2024-012',
        status: 'approved',
        organizerId,
        submittedAt: '2024-11-15T12:00:00Z',
        decisionAt: '2024-11-20T14:00:00Z',
      },
      {
        id: 'evt-13',
        title: 'Gastroenterology Update',
        titleEn: 'Gastroenterology Update',
        titleAr: '   ',
        organizerEn: 'Digestive Health Center',
        organizerAr: '   ',
        descriptionEn: 'GI disorders latest.',
        descriptionAr: '   ',
        date: '2026-01-10',
        locationEn: 'Dammam - GI Center',
        locationAr: ' -   ',
        city: 'Dammam',
        specialty: 'Gastroenterology',
        activityType: 'Seminar',
        cme_hours: 6,
        sfda_license: 'MDS-REQ-2024-013',
        status: 'draft',
        organizerId,
        submittedAt: '2024-11-25T09:00:00Z',
        decisionAt: '2024-11-28T11:00:00Z',
        rejectionReason: 'Insufficient CME hours',
        rejectionCategory: 'CME Requirements',
      },
      {
        id: 'evt-14',
        title: 'Urology Conference',
        titleEn: 'Urology Conference',
        titleAr: '  ',
        organizerEn: 'Urological Center',
        organizerAr: ' ',
        descriptionEn: 'Urological advances.',
        descriptionAr: '  ',
        date: '2026-02-15',
        locationEn: 'Riyadh - Urology Institute',
        locationAr: ' -   ',
        city: 'Riyadh',
        specialty: 'urology',
        activityType: 'Conference',
        cme_hours: 13,
        sfda_license: 'MDS-REQ-2024-014',
        status: 'approved',
        organizerId,
        submittedAt: '2024-12-01T10:00:00Z',
        decisionAt: '2024-12-06T16:00:00Z',
      },
      {
        id: 'evt-15',
        title: 'Ophthalmology Course',
        titleEn: 'Ophthalmology Course',
        titleAr: '  ',
        organizerEn: 'Eye Care Center',
        organizerAr: '  ',
        descriptionEn: 'Eye care techniques.',
        descriptionAr: '  ',
        date: '2026-03-20',
        locationEn: 'Jeddah - Eye Institute',
        locationAr: ' -  ',
        city: 'Jeddah',
        specialty: 'ophthalmology',
        activityType: 'Course',
        cme_hours: 11,
        sfda_license: 'MDS-REQ-2024-015',
        status: 'approved',
        organizerId,
        submittedAt: '2024-12-05T08:00:00Z',
        decisionAt: '2024-12-10T13:00:00Z',
      },
      {
        id: 'evt-16',
        title: 'Rheumatology Seminar',
        titleEn: 'Rheumatology Seminar',
        titleAr: ' ',
        organizerEn: 'Rheumatology Center',
        organizerAr: ' ',
        descriptionEn: 'Arthritis management.',
        descriptionAr: '  ',
        date: '2026-04-10',
        locationEn: 'Dammam - Rheumatology Institute',
        locationAr: ' -  ',
        city: 'Dammam',
        specialty: 'Rheumatology',
        activityType: 'Seminar',
        cme_hours: 7,
        sfda_license: 'MDS-REQ-2024-016',
        status: 'draft',
        organizerId,
        submittedAt: '2024-12-08T14:00:00Z',
        decisionAt: '2024-12-11T10:00:00Z',
        rejectionReason: 'Missing faculty credentials',
        rejectionCategory: 'Faculty',
      },
      {
        id: 'evt-17',
        title: 'Pulmonology Workshop',
        titleEn: 'Pulmonology Workshop',
        titleAr: '   ',
        organizerEn: 'Lung Health Center',
        organizerAr: '  ',
        descriptionEn: 'Respiratory care updates.',
        descriptionAr: '   ',
        date: '2026-05-15',
        locationEn: 'Riyadh - Pulmonary Institute',
        locationAr: ' -  ',
        city: 'Riyadh',
        specialty: 'pulmonology',
        activityType: 'Workshop',
        cme_hours: 8,
        sfda_license: 'MDS-REQ-2024-017',
        status: 'approved',
        organizerId,
        submittedAt: '2024-12-12T09:00:00Z',
        decisionAt: '2024-12-17T15:00:00Z',
      },
      {
        id: 'evt-18',
        title: 'Nephrology Update',
        titleEn: 'Nephrology Update',
        titleAr: '  ',
        organizerEn: 'Kidney Care Center',
        organizerAr: '  ',
        descriptionEn: 'Kidney disease management.',
        descriptionAr: '  ',
        date: '2026-06-01',
        locationEn: 'Jeddah - Nephrology Institute',
        locationAr: ' -  ',
        city: 'Jeddah',
        specialty: 'Nephrology',
        activityType: 'Seminar',
        cme_hours: 6,
        sfda_license: 'MDS-REQ-2024-018',
        status: 'approved',
        organizerId,
        submittedAt: '2024-12-15T11:00:00Z',
        decisionAt: '2024-12-20T14:00:00Z',
      },
      {
        id: 'evt-19',
        title: 'Hematology Conference',
        titleEn: 'Hematology Conference',
        titleAr: '  ',
        organizerEn: 'Blood Disorders Center',
        organizerAr: '  ',
        descriptionEn: 'Blood disorders treatment.',
        descriptionAr: '  ',
        date: '2026-07-10',
        locationEn: 'Dammam - Hematology Institute',
        locationAr: ' -   ',
        city: 'Dammam',
        specialty: 'hematology',
        activityType: 'Conference',
        cme_hours: 17,
        sfda_license: 'MDS-REQ-2024-019',
        status: 'draft',
        organizerId,
        submittedAt: '2024-12-18T10:00:00Z',
        decisionAt: '2024-12-22T12:00:00Z',
        rejectionReason: 'Incomplete agenda',
        rejectionCategory: 'Agenda',
      },
      {
        id: 'evt-20',
        title: 'Infectious Diseases Update',
        titleEn: 'Infectious Diseases Update',
        titleAr: '  ',
        organizerEn: 'Infection Control Center',
        organizerAr: '  ',
        descriptionEn: 'Infection prevention.',
        descriptionAr: '  ',
        date: '2026-08-15',
        locationEn: 'Riyadh - Infection Institute',
        locationAr: ' -  ',
        city: 'Riyadh',
        specialty: 'infectious_diseases',
        activityType: 'Seminar',
        cme_hours: 5,
        sfda_license: 'MDS-REQ-2024-020',
        status: 'approved',
        organizerId,
        submittedAt: '2024-12-20T08:00:00Z',
        decisionAt: '2024-12-25T16:00:00Z',
      },
      // Additional events for Monitoring (8+ items requirement - published/closed)
      {
        id: 'evt-21',
        title: 'Anesthesiology Course',
        titleEn: 'Anesthesiology Course',
        titleAr: ' ',
        organizerEn: 'Anesthesia Center',
        organizerAr: ' ',
        descriptionEn: 'Anesthesia techniques.',
        descriptionAr: ' ',
        date: '2024-11-01', // Past date for monitoring
        locationEn: 'Jeddah - Anesthesia Institute',
        locationAr: ' -  ',
        city: 'Jeddah',
        specialty: 'Anesthesiology',
        activityType: 'Course',
        cme_hours: 12,
        sfda_license: 'MDS-REQ-2024-021',
        status: 'published',
        organizerId,
        submittedAt: '2024-09-01T10:00:00Z',
        decisionAt: '2024-09-05T14:00:00Z',
      },
      {
        id: 'evt-22',
        title: 'Radiology Workshop',
        titleEn: 'Radiology Workshop',
        titleAr: '  ',
        organizerEn: 'Imaging Center',
        organizerAr: ' ',
        descriptionEn: 'Medical imaging advances.',
        descriptionAr: '  ',
        date: '2024-10-15', // Past date
        locationEn: 'Dammam - Radiology Institute',
        locationAr: ' -  ',
        city: 'Dammam',
        specialty: 'radiology',
        activityType: 'Workshop',
        cme_hours: 9,
        sfda_license: 'MDS-REQ-2024-022',
        status: 'published',
        organizerId,
        submittedAt: '2024-08-15T09:00:00Z',
        decisionAt: '2024-08-20T15:00:00Z',
      },
      {
        id: 'evt-23',
        title: 'Pathology Seminar',
        titleEn: 'Pathology Seminar',
        titleAr: '  ',
        organizerEn: 'Pathology Center',
        organizerAr: '  ',
        descriptionEn: 'Diagnostic pathology.',
        descriptionAr: '  ',
        date: '2024-09-20', // Past date
        locationEn: 'Riyadh - Pathology Institute',
        locationAr: ' -   ',
        city: 'Riyadh',
        specialty: 'pathology',
        activityType: 'Seminar',
        cme_hours: 6,
        sfda_license: 'MDS-REQ-2024-023',
        status: 'published',
        organizerId,
        submittedAt: '2024-07-20T11:00:00Z',
        decisionAt: '2024-07-25T13:00:00Z',
      },
      {
        id: 'evt-24',
        title: 'Internal Medicine Update',
        titleEn: 'Internal Medicine Update',
        titleAr: '  ',
        organizerEn: 'Internal Medicine Center',
        organizerAr: '  ',
        descriptionEn: 'General medicine updates.',
        descriptionAr: '  ',
        date: '2024-08-10', // Past date
        locationEn: 'Jeddah - Internal Medicine Institute',
        locationAr: ' -   ',
        city: 'Jeddah',
        specialty: 'internal_medicine',
        activityType: 'Seminar',
        cme_hours: 7,
        sfda_license: 'MDS-REQ-2024-024',
        status: 'published',
        organizerId,
        submittedAt: '2024-06-10T10:00:00Z',
        decisionAt: '2024-06-15T14:00:00Z',
      },
      {
        id: 'evt-25',
        title: 'Obstetrics Conference',
        titleEn: 'Obstetrics Conference',
        titleAr: ' ',
        organizerEn: 'Maternity Center',
        organizerAr: ' ',
        descriptionEn: 'Maternal care advances.',
        descriptionAr: '  ',
        date: '2024-07-05', // Past date
        locationEn: 'Dammam - Maternity Institute',
        locationAr: ' -  ',
        city: 'Dammam',
        specialty: 'Obstetrics',
        activityType: 'Conference',
        cme_hours: 15,
        sfda_license: 'MDS-REQ-2024-025',
        status: 'published',
        organizerId,
        submittedAt: '2024-05-05T09:00:00Z',
        decisionAt: '2024-05-10T16:00:00Z',
      },
      {
        id: 'evt-26',
        title: 'Gynecology Workshop',
        titleEn: 'Gynecology Workshop',
        titleAr: '   ',
        organizerEn: 'Women Health Center',
        organizerAr: '  ',
        descriptionEn: 'Women health care.',
        descriptionAr: '  ',
        date: '2024-06-15', // Past date
        locationEn: 'Riyadh - Gynecology Institute',
        locationAr: ' -   ',
        city: 'Riyadh',
        specialty: 'gynecology',
        activityType: 'Workshop',
        cme_hours: 10,
        sfda_license: 'MDS-REQ-2024-026',
        status: 'published',
        organizerId,
        submittedAt: '2024-04-15T08:00:00Z',
        decisionAt: '2024-04-20T12:00:00Z',
      },
      {
        id: 'evt-27',
        title: 'ENT Update',
        titleEn: 'ENT Update',
        titleAr: '   ',
        organizerEn: 'ENT Center',
        organizerAr: '   ',
        descriptionEn: 'Ear, nose, throat care.',
        descriptionAr: '   ',
        date: '2024-05-20', // Past date
        locationEn: 'Jeddah - ENT Institute',
        locationAr: ' -    ',
        city: 'Jeddah',
        specialty: 'ent',
        activityType: 'Seminar',
        cme_hours: 8,
        sfda_license: 'MDS-REQ-2024-027',
        status: 'published',
        organizerId,
        submittedAt: '2024-03-20T10:00:00Z',
        decisionAt: '2024-03-25T15:00:00Z',
      },
      {
        id: 'evt-28',
        title: 'Plastic Surgery Course',
        titleEn: 'Plastic Surgery Course',
        titleAr: '  ',
        organizerEn: 'Plastic Surgery Center',
        organizerAr: '  ',
        descriptionEn: 'Cosmetic surgery techniques.',
        descriptionAr: '  ',
        date: '2024-04-10', // Past date - more than 21 days ago for compliance alert
        locationEn: 'Dammam - Plastic Surgery Institute',
        locationAr: ' -   ',
        city: 'Dammam',
        specialty: 'plastic_surgery',
        activityType: 'Course',
        cme_hours: 14,
        sfda_license: 'MDS-REQ-2024-028',
        status: 'closed',
        organizerId,
        submittedAt: '2024-02-10T09:00:00Z',
        decisionAt: '2024-02-15T13:00:00Z',
      },
      {
        id: 'evt-29',
        title: 'Future Cardiology Conference',
        titleEn: 'Future Cardiology Conference',
        titleAr: '  ',
        organizerEn: 'Cardiac Institute',
        organizerAr: ' ',
        descriptionEn: 'Upcoming cardiology event.',
        descriptionAr: '  ',
        date: '2025-12-15', // Future date for upcoming events
        locationEn: 'Riyadh - Medical Center',
        locationAr: ' -  ',
        city: 'Riyadh',
        specialty: 'cardiology',
        activityType: 'Conference',
        cme_hours: 16,
        sfda_license: 'MDS-REQ-2024-029',
        status: 'approved',
        organizerId,
        submittedAt: '2024-12-20T10:00:00Z',
        decisionAt: '2024-12-25T14:00:00Z',
      },
    ],
    assignments: [
      {
        id: assignmentId,
        eventId,
        organizerId,
        eventManagerId,
        status: 'pending',
      },
      {
        id: 'assign-2',
        eventId: 'evt-3',
        organizerId,
        eventManagerId,
        status: 'accepted',
      },
      {
        id: 'assign-3',
        eventId: 'evt-6',
        organizerId,
        eventManagerId,
        status: 'accepted',
      },
      {
        id: 'assign-4',
        eventId: 'evt-7',
        organizerId,
        eventManagerId,
        status: 'pending',
      },
      {
        id: 'assign-5',
        eventId: 'evt-8',
        organizerId,
        eventManagerId,
        status: 'accepted',
      },
      {
        id: 'assign-6',
        eventId: 'evt-10',
        organizerId,
        eventManagerId,
        status: 'pending',
      },
      {
        id: 'assign-7',
        eventId: 'evt-11',
        organizerId,
        eventManagerId,
        status: 'declined',
      },
      {
        id: 'assign-8',
        eventId: 'evt-12',
        organizerId,
        eventManagerId,
        status: 'accepted',
      },
    ],
    tickets: [
      {
        id: ticketId,
        eventId,
        hcpId,
        status: 'confirmed',
      },
      {
        id: 'tkt-2',
        eventId: 'evt-3',
        hcpId,
        status: 'attended',
      },
      {
        id: 'tkt-3',
        eventId: 'evt-3',
        hcpId: 'hcp-2',
        status: 'attended',
      },
      {
        id: 'tkt-4',
        eventId: 'evt-6',
        hcpId,
        status: 'attended',
      },
      {
        id: 'tkt-5',
        eventId: 'evt-6',
        hcpId: 'hcp-2',
        status: 'confirmed',
      },
      {
        id: 'tkt-6',
        eventId: 'evt-8',
        hcpId,
        status: 'attended',
      },
      {
        id: 'tkt-7',
        eventId: 'evt-8',
        hcpId: 'hcp-2',
        status: 'attended',
      },
      {
        id: 'tkt-8',
        eventId: 'evt-12',
        hcpId,
        status: 'confirmed',
      },
      {
        id: 'tkt-9',
        eventId: 'evt-28',
        hcpId,
        status: 'attended',
      },
    ],
    attendanceRecords: [
      {
        id: attendanceId,
        ticketId,
        finalized: false,
      },
      {
        id: 'att-2',
        ticketId: 'tkt-2',
        finalized: true,
      },
      {
        id: 'att-3',
        ticketId: 'tkt-3',
        finalized: true,
      },
      {
        id: 'att-4',
        ticketId: 'tkt-4',
        finalized: true,
      },
      {
        id: 'att-5',
        ticketId: 'tkt-6',
        finalized: true,
      },
      {
        id: 'att-6',
        ticketId: 'tkt-7',
        finalized: true,
      },
      {
        id: 'att-7',
        ticketId: 'tkt-9',
        finalized: false, // Not finalized - will trigger compliance alert
      },
    ],
    certificates: [
      {
        id: certificateId,
        eventId,
        ticketId,
        hcpId,
        issuedAt: '2025-01-20T10:00:00Z',
        cme_hours: 12,
        verified: true,
      },
      {
        id: 'cert-2',
        eventId: 'evt-6',
        ticketId: 'tkt-4',
        hcpId,
        issuedAt: '2025-02-15T14:30:00Z',
        cme_hours: 8,
        verified: true,
      },
      {
        id: 'cert-3',
        eventId: 'evt-8',
        ticketId: 'tkt-6',
        hcpId,
        issuedAt: '2025-03-10T09:00:00Z',
        cme_hours: 6,
        verified: true,
      },
    ],
    reviews: [
      {
        id: reviewId,
        eventId,
        hcpId,
        rating: 5,
        text: 'Excellent event with high-quality content and outstanding speakers.',
        createdAt: '2025-01-25T12:00:00Z',
      },
      {
        id: 'rev-2',
        eventId: 'evt-6',
        hcpId,
        rating: 4,
        text: 'Very informative workshop, well organized.',
        createdAt: '2025-02-20T15:30:00Z',
      },
    ],
    sponsorships: [
      {
        id: sponsorshipId,
        eventId,
        vendorId,
        status: 'purchased',
      },
    ],
  };
}
